version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres17
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data-db/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - odoo19-net

  odoo19:
    build: .
    container_name: odoo19
    depends_on:
      db:
        condition: service_healthy   # ✅ Wait for Postgres to be ready
    ports:
      - "8090:8090"
    volumes:
      - ./odoo_extra_addons:/opt/odoo/odoo_extra_addons
      - ./extra_addons:/opt/odoo/extra_addons
      - ./vendor_addons:/opt/odoo/vendor_addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./odoo-data:/opt/odoo/data
      - ./odoo-log:/var/log/odoo
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    command: >
      python odoo/odoo-bin -c /etc/odoo/odoo.conf
      -u account_reconcile_model_oca,account_reconcile_oca,zervi_account_asset,manufacture_process_costing,bi_lot_and_serial_expiry_report_track,uom_conversion,cr_product_lot_serial
      -d odoo
    restart: always
    networks:
      - odoo19-net

volumes:
  odoo-data:

networks:
  odoo19-net:
    driver: bridge
