version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"   # access pgAdmin at http://localhost:5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    networks:
      - odoo19_odoo19-net

volumes:
  pgadmin-data:

networks:
  odoo19_odoo19-net:
    external: true
